spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql
    initialization-mode: never
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      javax:
        persistance:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: schema-mysql.sql
